services:
  backend:
    build:
      context: ./app/backend       # <--- контекстом делаем сам backend
      dockerfile: Dockerfile
    container_name: debate-backend
    environment:
      AIML_BASE_URL: ${AIML_BASE_URL:-https://api.aimlapi.com/v1}
      AIML_API_KEY: ${AIML_API_KEY:-}
      AIML_MODEL: ${AIML_MODEL:-openai/gpt-5-nano-2025-08-07}
      TAVILY_API_KEY: ${TAVILY_API_KEY:-}
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend:/app         # dev-монтаж кода
    profiles: ["dev"]

  tests:
    build:
      context: ./app/backend       # <--- тот же контекст
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      AIML_BASE_URL: ${AIML_BASE_URL:-https://api.aimlapi.com/v1}
      AIML_API_KEY: ${AIML_API_KEY:-}
      AIML_MODEL: ${AIML_MODEL:-openai/gpt-5-nano-2025-08-07}
      TAVILY_API_KEY: ${TAVILY_API_KEY:-}
    volumes:
      - ./app/backend:/app
    command: ["python","-m","pytest","-q"]
    profiles: ["test"]