version: "3.9"

services:
  backend:
    build:
      context: ./app/backend
    command: uvicorn src.main:create_app --host 0.0.0.0 --port 8000 --factory
    ports:
      - "8000:8000"
    environment:
      LLM_FORCE_STUB: "0" 
      AIML_BASE_URL: ${AIML_BASE_URL}
      AIML_API_KEY: ${AIML_API_KEY}
      AIML_MODEL_NANO: ${AIML_MODEL_NANO}
      AIML_MODEL_HEAVY: ${AIML_MODEL_HEAVY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
    working_dir: /app
    restart: unless-stopped
    profiles: ["dev"]

  tests:
    build:
      context: ./app/backend 
      dockerfile: Dockerfile
    environment:
      AIML_BASE_URL: ${AIML_BASE_URL}
      AIML_API_KEY: ${AIML_API_KEY}
      AIML_MODEL_NANO: ${AIML_MODEL_NANO}
      AIML_MODEL_HEAVY: ${AIML_MODEL_HEAVY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
    working_dir: /app
    command: ["python","-m","pytest","-q"]
    profiles: ["test"]