version: "3.9"

services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    env_file: ./.env
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "${HOST_PORT:-8001}:8000"
    environment:
      AIMLAPI_BASE_URL: ${AIML_BASE_URL}
      AIMLAPI_API_KEY: ${AIML_API_KEY}
      SMOL_MODEL: ${AIML_MODEL_NANO}
      CHEAP_MODEL: ${AIML_MODEL_NANO}
      MAIN_MODEL: ${AIML_MODEL_HEAVY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      APP_PORT: "8000"
    restart: unless-stopped
    profiles: ["dev"]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 20s

  tests:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    env_file: ./.env
    working_dir: /app
    environment:
      AIMLAPI_BASE_URL: ${AIML_BASE_URL}
      AIMLAPI_API_KEY: ${AIML_API_KEY}
      SMOL_MODEL: ${AIML_MODEL_NANO}
      CHEAP_MODEL: ${AIML_MODEL_NANO}
      MAIN_MODEL: ${AIML_MODEL_HEAVY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
    # run the real test suite:
    command: ["pytest","-q"]
    profiles: ["test"]
