version: "3.9"

services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    env_file: ./.env
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      AIMLAPI_BASE_URL: ${AIML_BASE_URL}
      AIMLAPI_API_KEY: ${AIML_API_KEY}
      SMOL_MODEL: ${AIML_MODEL_NANO}
      CHEAP_MODEL: ${AIML_MODEL_NANO}
      MAIN_MODEL: ${AIML_MODEL_HEAVY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      APP_PORT: "8000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8001/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    environment:
      # фронт ходит внутрь сети на backend-сервис
      NEXT_PUBLIC_BACKEND_URL: http://backend:8001/api
      NODE_ENV: production
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

  gateway:
    image: nginx:1.25-alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "8080:80"   
    volumes:
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  tests:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    env_file: ./.env
    working_dir: /app
    environment:
      AIMLAPI_BASE_URL: ${AIML_BASE_URL}
      AIMLAPI_API_KEY: ${AIML_API_KEY}
      SMOL_MODEL: ${AIML_MODEL_NANO}
      CHEAP_MODEL: ${AIML_MODEL_NANO}
      MAIN_MODEL: ${AIML_MODEL_HEAVY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
    command: ["pytest","-q"]
    profiles: ["test"]
