services:
  # --- Backend (FastAPI via Docker) ---
  - type: web
    name: debate-backend
    runtime: docker
    dockerContext: .
    dockerfilePath: app/backend/Dockerfile
    autoDeployTrigger: commit
    envVars:
      - key: CORS_ORIGINS
        fromService:
          name: debate-frontend-ssr
          type: web
          envVarKey: RENDER_EXTERNAL_URL

  # --- Frontend (Next.js SSR) ---
  - type: web
    name: debate-frontend-ssr   
    runtime: node
    rootDir: app/frontend
    buildCommand: npm ci && npm run build
    startCommand: npm run start -- -p $PORT
    autoDeployTrigger: commit
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: debate-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
