services:
  # --- Backend (Docker) ---
  - type: web
    name: debate-backend
    runtime: docker
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    plan: free
    autoDeployTrigger: commit
    envVars:
      - key: PORT
        value: "8000"                  
      - key: CORS_ORIGINS
        value: https://debate-frontend.onrender.com

  # --- Frontend (Static Site) ---
  - type: web
    name: debate-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    autoDeployTrigger: commit
    envVars:
      - key: VITE_API_URL             
        value: https://debate-backend.onrender.com
    routes:
      - type: rewrite                
        source: "/*"
        destination: "/index.html"
