services:
  # --- Backend (FastAPI via Docker) ---
  - type: web
    name: debate-backend
    runtime: docker
    dockerContext: .
    rootDir: app/backend      
    dockerfilePath: Dockerfile
    autoDeployTrigger: commit
    envVars:
      - key: CORS_ORIGINS
        fromService:
          name: debate-frontend
          type: web
          envVarKey: RENDER_EXTERNAL_URL

  # --- Frontend (Next.js static export) ---
  - type: web
    name: debate-frontend-static
    runtime: static
    rootDir: app/frontend
    buildCommand: npm ci && npm run build && npm run export
    staticPublishPath: out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: debate-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
