services:
  - type: web
    name: debate-mate-api
    env: docker
    rootDir: app/backend
    dockerfilePath: Docker
    plan: free
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 8080
      - key: AIML_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: AIML_BASE_URL
        sync: false
      - key: AIML_MODEL_NANO
        sync: false
      - key: AIML_MODEL_HEAVY
        sync: false

  - type: web
    name: debate-mate-web-ssr
    env: docker
    rootDir: app/frontend
    dockerfilePath: Docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NEXT_PUBLIC_BACKEND_ORIGIN
        fromService:
          type: web
          name: debate-mate-api
          property: url
      - key: NEXT_PUBLIC_BACKEND_URL
        value: /api
      - key: PORT
        value: 3000
