services:
  - type: web
    name: debate-coach-api
    env: docker
    rootDir: app/backend
    dockerfilePath: app/backend/Docker
    plan: free
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 8080
      - key: AIML_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: AIML_BASE_URL
        sync: false
      - key: AIML_MODEL_NANO
        sync: false
      - key: AIML_MODEL_HEAVY
        sync: false

  - type: web
    name: debate-coach-web
    env: docker
    rootDir: app/frontend
    dockerfilePath: app/frontend/Docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NEXT_PUBLIC_BACKEND_HOST
        fromService:
          type: web
          name: debate-coach-api
          property: host
      - key: NEXT_PUBLIC_BACKEND_URL
        value: /api
      - key: PORT
        value: 3000